version: "3"
services:
  # app:
  #   build: .
  #   command: npm run dev
  #   volumes:
  #     - .:/usr/src/app/
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://project-bright-red-user:project-bright-red-pwd@postgres:5432/project-bright-red-db
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: project-bright-red-db
      POSTGRES_USER: project-bright-red-user
      POSTGRES_PASSWORD: project-bright-red-pwd
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
