version: "3"
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - app:/adonis
      - nodemodules:/adonis/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://project-bright-red-user:project-bright-red-pwd@postgres:5432/project-bright-red-db
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: project-bright-red-db
      POSTGRES_USER: project-bright-red-user
      POSTGRES_PASSWORD: project-bright-red-pwd
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
volumes:
  data: {}
  app: {}
  nodemodules: {}
